services:
  - type: web
    name: apex-tracker
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: APEX_EMAIL
        sync: false
      - key: APEX_PASSWORD
        sync: false
      - key: APEX_ACCOUNT_ID
        value: PA-APEX-383013-03
      - key: APEX_TOTP_SECRET
        sync: false
